config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#index'
  get '/secret', to: 'pages#secret', as: :secret
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable, :zxcvbnable

  def send_devise_notification(notification, *args)
    devise_mailer.send(notification, self, *args).deliver_later
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: [:secret]
end

app/helpers/application_helper.rb
module ApplicationHelper
  def header(text)
    content_for(:header) { text.to_s }
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeviseDemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <%= link_to 'Devise Demo', root_path, class: 'navbar-brand' %>
            </div>
            <div id="navbar">
                <ul class="nav navbar-nav">
                    <li><%= link_to 'Home', root_path %></li>
                </ul>
                <ul class="nav navbar-nav pull-right">
                    <% if user_signed_in? %>
                        <li><%= link_to 'Secret', secret_path %></li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <%= current_user.name %>
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" role="menu">
                                <li><%= link_to 'Profile', edit_user_registration_path %></li>
                                <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
                            </ul>
                        </li>
                    <% else %>
                        <li><%= link_to 'Log In', new_user_session_path %></li>
                        <li><%= link_to 'Sign Up', new_user_registration_path %></li>
                    <% end %>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        <% flash.each do |key, value| %>
            <div class="alert alert-<%= key %>">
                <%= value %>
            </div>
        <% end %>
    </div>
    <%= yield :top_content %>
    <div class="container">
        <h1><%= yield :header %></h1>
        <%= yield %>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<% content_for :top_content do %>
    <div class="jumbotron">
        <div class="container">
            <h1>Welcome!</h1>
            <p>Register to get started.</p>
            <p>
                <%= link_to 'Register', new_user_registration_path, class: 'btn btn-primary btn-lg' %>
            </p>
        </div>
    </div>
<% end %>

app/views/pages/secret.html.erb
<% header "Secret!" %>